### ISSUE TITLE
ERROR in Block-scoped declarations (let, const, function, class) not yet supported outside strict mode

### ISSUE THREAD

**Issue by liu-dongyu** [tomasAlabes/stylefmt-loader#1]
When using stylefmt-loader, it show me an error msg like `ERROR in Block-scoped declarations (let, const, function, class) not yet supported outside strict mode`. What is that mean? Did i do something wrong or miss anything?
![2016-09-07 10-33-40](https://cloud.githubusercontent.com/assets/16187601/18297854/98f8f26a-74e6-11e6-8e31-3dad3a8db4b1.png)
![2016-09-07 10-33-05](https://cloud.githubusercontent.com/assets/16187601/18297857/9a15ee00-74e6-11e6-8613-879ec5ce6320.png)
![2016-09-07 10-32-47](https://cloud.githubusercontent.com/assets/16187601/18297858/9aecb1e2-74e6-11e6-8e17-b3e99d388e28.png)

**Comment by tomasAlabes** [comment]
Seems like my code contains let/const without a "use strict" in it. I'm in a work trip so I can't fix it now but could you try with that?

**Comment by tomasAlabes** [comment]
Fixed in 1.0.1. Thanks for the report.
