### ISSUE TITLE
Error: Cannot find module 'stylefmt'

### ISSUE THREAD

**Issue by oleksiibilous** [tomasAlabes/stylefmt-loader#7]
Hello

I'm trying to integrate stylefmt-loader with my webpack 2 config. Here is my configuration:

```
{
        exclude: /node_modules/,
        test: fileExtensions.css,
        use: [
          'style-loader',
          {
            loader: 'css-loader',
            options: {
              importLoaders: 1,
              modules: true,
            },
          },
          'postcss-loader',
          'stylefmt-loader',
        ]
      },
```

But I'm getting the error `Error: Cannot find module 'stylefmt'`

**Comment by tomasAlabes** [comment]
`npm install stylefmt --save-dev` ?

**Comment by oleksiibilous** [comment]
Of course I've installed it first😄

**Comment by oleksiibilous** [comment]
Does this package support `Webpack 2`?

**Comment by tomasAlabes** [comment]
Yes. And stylefmt is a peer dependency of this loader.

**Comment by oleksiibilous** [comment]
Hmm...Will checkout everything again and will let you know. Thanks for the quick respond

**Comment by oleksiibilous** [comment]
Yes, you are right. I've installed `stylefmt` into the wrong `package.json`. Thanks for your help and for your work
